services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: Mysql
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "3080:3080"
    env_file:
      - ./server/.env.docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      args:
        - VITE_API_BASE_URL=http://localhost:3080
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
